using YoutubeExplode;
using YoutubeExplode.Playlists;
using YoutubeExplode.Common;
using YoutubeExplode.Videos;
using YoutubeSubScraper.Persistence;

namespace YoutubeSubScraper;

public static class Youtube
{
    public static async Task<List<string>> GetVideoUrlsFromPlaylistUrl(string playlistUrl)
    {
        var youtube = new YoutubeClient();
        try
        {
            var playlistId = PlaylistId.Parse(playlistUrl);
            var videos = await youtube.Playlists.GetVideosAsync(playlistId);

            return videos
                .Select(video => $"https://www.youtube.com/watch?v={video.Id}")
                .ToList();
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred in {nameof(GetVideoUrlsFromPlaylistUrl)} method: {ex.Message}");
        }
        return new List<string>();
    }
    
    public static async Task<List<BombaSubtitles>> GetCaptionsForVideo(string videoUrl)
    {
        try
        {
            var youtube = new YoutubeClient();
            var videoId = VideoId.Parse(videoUrl);
            var video = await youtube.Videos.GetAsync(videoId);

            var trackManifest = await youtube.Videos.ClosedCaptions.GetManifestAsync(videoId);

            var trackInfo = trackManifest.Tracks.FirstOrDefault(t => t.Language.Code == "pl" && !t.IsAutoGenerated);
            var tracksLanguages = string.Join(", ", trackManifest.Tracks.Select(x => x.Language)) ?? "";
            
            Console.WriteLine($"{video.Title}\nFound subtitles: {tracksLanguages}\n\n");

            if (trackInfo != null)
            {
                var track = await youtube.Videos.ClosedCaptions.GetAsync(trackInfo);

                return track
                    .Captions
                    .Select(c => new BombaSubtitles(video.Title, videoUrl, c.Text, c.Offset))
                    .ToList();
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred in {nameof(GetCaptionsForVideo)} method: {ex.Message}");
        }
        return [];
    }
}